manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: llmerlos
      url-base: https://github.com/llmerlos
  projects:
    - name: zmk
      remote: llmerlos 
      revision: main
      import: app/west.yml
  self:
    path: config
